### ISSUE TITLE
image_utils: handle remainders in split_multiple_writes: 

### ISSUE THREAD

**Issue by YongpingGao** [big-data-lab-team/mapreduce#12]
### split_multiple_writes: handle remainders after splitting properly

```python
if X_size % X_splits != 0 or Z_size % Z_splits != 0 or Y_size % Y_splits != 0:
    raise Exception("There is remainder after splitting, please reset the y,z,x splits")
```

Split number set by user may cause remainder(not the same size with other splits) in the splitting phase. We should handle this properly instead of just raising an exception.

**Comment by ValHayot** [comment]
transferred issue to https://github.com/big-data-lab-team/sam/
